If you run all tests at the same time, you will get the following error:

>javax.persistence.PersistenceException: org.hibernate.HibernateException: The internal connection pool has reached its maximum size and no connection is currently available!


I don't know how to fix it yet.